"""empty message

Revision ID: 09e69ce87711
Revises: a41b860d6bad
Create Date: 2019-10-30 20:27:32.029944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e69ce87711'
down_revision = 'a41b860d6bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('change_seqnum', sa.Integer(), nullable=False, comment='Updated when a received `AccountChangeSignal` is applied.'),
    sa.Column('change_ts', sa.TIMESTAMP(timezone=True), nullable=False, comment='Updated when a received `AccountChangeSignal` is applied.'),
    sa.Column('principal', sa.BigInteger(), nullable=False, comment='The total owed amount. Can be negative.'),
    sa.Column('interest', sa.FLOAT(), nullable=False, comment='The amount of interest accumulated on the account before `change_ts`, but not added to the `principal` yet. Can be a negative number. `interest`gets zeroed and added to the principal once in a while (like once per week).'),
    sa.Column('interest_rate', sa.REAL(), nullable=False, comment='Annual rate (in percents) at which interest accumulates on the account.'),
    sa.Column('last_outgoing_transfer_date', sa.DATE(), nullable=True, comment='Updated on each transfer for which this account is the sender. This field is not updated on demurrage payments.'),
    sa.Column('status', sa.SmallInteger(), nullable=False, comment='Additional account status flags.'),
    sa.Column('interest_rate_last_change_seqnum', sa.Integer(), nullable=False, comment='Incremented (with wrapping) on each invocation of the `change_interest_rate` actor.'),
    sa.Column('interest_rate_last_change_ts', sa.TIMESTAMP(timezone=True), nullable=False, comment='Updated on every increment of `interest_rate_last_change_seqnum`. Must never decrease.'),
    sa.CheckConstraint('interest_rate > -100.0 AND interest_rate <= 100.0'),
    sa.CheckConstraint('principal > -9223372036854775808'),
    sa.PrimaryKeyConstraint('debtor_id', 'creditor_id'),
    comment='Tells who owes what to whom. This table is a replica the table with the same name in the `swpt_accounts` service.'
    )
    op.create_table('change_interest_rate_signal',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('change_seqnum', sa.Integer(), nullable=False),
    sa.Column('change_ts', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interest_rate', sa.REAL(), nullable=False),
    sa.PrimaryKeyConstraint('debtor_id', 'signal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('change_interest_rate_signal')
    op.drop_table('account')
    # ### end Alembic commands ###
