"""empty message

Revision ID: a2f7d66208c9
Revises: a76b673cbd03
Create Date: 2023-08-18 14:32:13.105756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f7d66208c9'
down_revision = 'a76b673cbd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configure_account_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('negligible_amount', sa.REAL(), nullable=True))

    op.execute("UPDATE configure_account_signal SET negligible_amount = 1e30")

    with op.batch_alter_table('configure_account_signal', schema=None) as batch_op:
        batch_op.alter_column('negligible_amount', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configure_account_signal', schema=None) as batch_op:
        batch_op.drop_column('negligible_amount')

    # ### end Alembic commands ###
