"""empty message

Revision ID: a76b673cbd03
Revises: 2651707e9ee2
Create Date: 2023-08-18 14:00:42.380239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76b673cbd03'
down_revision = '2651707e9ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debtor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_balance', sa.BigInteger(), nullable=True))

    op.execute("UPDATE debtor SET min_balance = -9223372036854775808")

    with op.batch_alter_table('debtor', schema=None) as batch_op:
        batch_op.alter_column('min_balance', nullable=False)

    op.create_check_constraint('min_balance_check', 'debtor', 'min_balance <= 0')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debtor', schema=None) as batch_op:
        batch_op.drop_column('min_balance')

    # ### end Alembic commands ###
