"""empty message

Revision ID: bec205883543
Revises: 263a81fa0dea
Create Date: 2021-02-17 13:49:58.093665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec205883543'
down_revision = '263a81fa0dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debtor', 'interest_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtor', sa.Column('interest_rate', sa.REAL(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
