"""empty message

Revision ID: c4d39767fca8
Revises: bec205883543
Create Date: 2021-05-05 13:04:47.934862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d39767fca8'
down_revision = 'bec205883543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debtor', sa.Column('debtor_info_iri', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debtor', 'debtor_info_iri')
    # ### end Alembic commands ###
