"""empty message

Revision ID: cac6fdb66c9c
Revises: c4d39767fca8
Create Date: 2021-05-06 16:39:41.718280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac6fdb66c9c'
down_revision = 'c4d39767fca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['debtor_id'], ['debtor.debtor_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('debtor_id', 'document_id'),
    comment='Represents a document saved by the debtor, which should remain available indefinitely, or at least for a very long time.'
    )
    op.add_column('debtor', sa.Column('documents_count', sa.Integer(), nullable=False))
    op.add_column('debtor', sa.Column('documents_count_reset_date', sa.DATE(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('debtor', 'documents_count_reset_date')
    op.drop_column('debtor', 'documents_count')
    op.drop_table('document')
    # ### end Alembic commands ###
